name: Publish zExcelGenerator to NuGet

on:
  push:
    tags:
      - 'zExcelGenerator-v*'   # ej: zExcelGenerator-v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: src/zExcelGenerator/zExcelGenerator.csproj
      NUGET_SOURCE: https://api.nuget.org/v3/index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # o la versiÃ³n que uses para build

      - name: Extract version from tag
        id: version
        run: |
          # github.ref_name = zExcelGenerator-v1.2.3
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#zExcelGenerator-v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore

      - name: Pack
        run: dotnet pack $PROJECT_PATH --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}

      - name: Push to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "$NUGET_SOURCE" --skip-duplicate
